language: php

php:
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
